### ISSUE TITLE
TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by paladox** [valhallasw/gerrit-reviewer-bot#11]
Hi in https://tools.wmflabs.org/gerrit-reviewer-bot/ it is getting this error

  File "pop3bot.py", line 121, in 
    add_reviewers(changeset['current_revision'], reviewers)
  File "/data/project/gerrit-reviewer-bot/src/gerrit-reviewer-bot/add_reviewer.py", line 128, in add_reviewers
    retval = subprocess.call(callcmd)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
Mon Aug 1 10:40:10 UTC 2016: Running as task 9353968 @ tools-exec-1410.eqiad.wmflabs
WARNING: /data/project/gerrit-reviewer-bot/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

**Comment by valhallasw** [comment]
Odd. Mostly because the bot seems to have worked without issues the next time -- the change that triggered this should not have been DELE'ed after a failure, but possibly the change was merged very quickly.

Unfortunately a massive change cleared the .out log, so I'm not sure which change triggered this, so I'm closing this task.
