### ISSUE TITLE
Gerrit reviewer bot dosent seem to be working

### ISSUE THREAD

**Issue by paladox** [valhallasw/gerrit-reviewer-bot#16]
Steps to reproduce

Create a change on for example integration/config.
Wait a few minutes and reload, you will notice that hashar hasent been added as reviewer.

Expected results
I expect the change to get hashar added automatically

Actual results
Hashar was not added, I had to manually add him.

Hi it seems that the gerrit reviewer bot is not working. Hashar was added to https://gerrit.wikimedia.org/r/#/c/328238/ automatically, i had to add him manually

**Comment by bd808** [comment]
```
Tue Dec 20 00:15:10 UTC 2016: Running as task 496796 @ tools-exec-1411.tools.eqiad.wmflabs
fatal: "I3b3b525225ce2571ca7e8233df5033d1efb86ceb" matches multiple changes
Traceback (most recent call last):
  File "pop3bot.py", line 154, in <module>
    main()
  File "pop3bot.py", line 148, in main
    add_reviewers(changeset['change_id'], reviewers)
  File "/mnt/nfs/labstore-secondary-tools-project/gerrit-reviewer-bot/src/gerrit-reviewer-bot/add_reviewer.py", line 139, in add_reviewers
    raise Exception(command + ' was not executed successfully (code %i)' % retval)
Exception: gerrit set-reviewers --add Paladox I3b3b525225ce2571ca7e8233df5033d1efb86ceb was not executed successfully (code 1)
```

**Comment by bd808** [comment]
```
Tue Dec 20 00:25:04 UTC 2016: Running as task 497070 @ tools-exec-1412.tools.eqiad.wmflabs
369 e-mails to process (5482 kB)
[MediaWiki-commits] [Gerrit] integration/uprightdiff[debian]:
        .gitreview: swap defaultbranch for track "Hashar (Code Review)" <gerrit@wikimedia.org> I3b3b525225ce2571ca7e8233df5033d1efb86ceb
(getting  117f70ece4444a0b9cf86483201fbb54d72da758 )

Processing changeset  I3b3b525225ce2571ca7e8233df5033d1efb86ceb .gitreview: swap defaultbranch for track by Hashar
u .gitreview
gerrit set-reviewers --add Paladox I3b3b525225ce2571ca7e8233df5033d1efb86ceb
<type 'exceptions.Exception'>
Done.
```

I think it is stuck because of that one bad commit with a duplicate change id. Looks like it blows up all processing of the queue.

**Comment by paladox** [comment]
Oh, thanks for looking into this. I wonder how we can fix that.

The problem is caused by https://github.com/valhallasw/gerrit-reviewer-bot/commit/2f5b48c404d371ef947ace0d197e3f3742ed2692 but it carnt be reverted due to a internal change in gerrit 2.13 which will still leave the bot broken. I doint know why we carnt use current_revision.

**Comment by paladox** [comment]
Thanks.
