### ISSUE TITLE
Gerrit-reviewer-bot got stuck for a few days

### ISSUE THREAD

**Issue by Dreamy-Jazz** [valhallasw/gerrit-reviewer-bot#27]
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/CheckUser/+/818517 should have had reviewer bot add reviewers to the change but it didn't do so.

**Comment by siebrand** [comment]
The mailing list engine puts some messages on hold for manual approval. It may well be that this was one of those changes. I may look into this at one point…

**Comment by valhallasw** [comment]
Seems like the job got stuck a few days ago and needed a manual restart. It should pick up your change when it starts processing again...

**Comment by valhallasw** [comment]
https://phabricator.wikimedia.org/T306391

@legoktm suggests there applying `timeout` to make sure the job doesn't run indefinitely. Under the old jobs framework the maximum runtime was an hour (I think) -- we could port it using that method.

**Comment by valhallasw** [comment]
Done in revision dcb3171
