### ISSUE TITLE
WARNING: SNIMissingWarning

### ISSUE THREAD

**Issue by paladox** [valhallasw/gerrit-reviewer-bot#9]
Hi https://tools.wmflabs.org/gerrit-reviewer-bot/

Is bringing up the below error

WARNING: /data/project/gerrit-reviewer-bot/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

WARNING: /data/project/gerrit-reviewer-bot/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by bd808** [comment]
This warning is caused by the urllib3 not liking the TLS library we have available on the Ubuntu Trusty hosts in Tool Labs (Python 2.7.6-8ubuntu0.2 + ssl 0.13-2ubuntu6). The warnings are harmless.

**Comment by paladox** [comment]
Oh ok thanks for responding.

**Comment by valhallasw** [comment]
I ran
`~/venv/bin/pip install --upgrade "requests[security]>=1.0"`
which should resolve this.

**Comment by paladox** [comment]
Thanks.
